/** Recorridos operativos UAT (discovery + SYGOS_3.0_PLAN_VALIDACION_FINAL.md). */
export type UatRecorrido = {
  id: string;
  title: string;
  discovery: string;
  priority: "nucleo" | "secundario";
  startHref: string;
  roles: string;
};

export const uatRecorridos: UatRecorrido[] = [
  {
    id: "R-01",
    title: "Cliente → EQUI → Atención → ingreso físico",
    discovery: "§4.1–4.2",
    priority: "nucleo",
    startHref: "/comercial/clientes/nuevo",
    roles: "qa.ventas.systron, qa.almacen.systron",
  },
  {
    id: "R-02",
    title: "Diagnóstico SYSTRON (EQUI) completo",
    discovery: "§4.3",
    priority: "nucleo",
    startHref: "/operacion/diagnosticos",
    roles: "qa.supervisor.systron, qa.tecnico.systron, qa.gerente.systron",
  },
  {
    id: "R-03",
    title: "Cotización desde diagnóstico validado",
    discovery: "§5",
    priority: "nucleo",
    startHref: "/comercial/cotizaciones?vista=pendientes-cotizar",
    roles: "qa.ceo, qa.ventas.systron",
  },
  {
    id: "R-04",
    title: "Cotización vendedor sin equipo físico",
    discovery: "§5",
    priority: "secundario",
    startHref: "/comercial/cotizaciones/nueva",
    roles: "qa.ventas.systron, qa.ceo",
  },
  {
    id: "R-05",
    title: "Reparación preautorizada + precio al terminar",
    discovery: "§4.4, §5",
    priority: "secundario",
    startHref: "/operacion/atenciones/nueva",
    roles: "qa.tecnico.systron, qa.gerente.systron, qa.ceo",
  },
  {
    id: "R-06",
    title: "MOT intercompañía (maestro)",
    discovery: "§4.1 MOT intercompañía",
    priority: "nucleo",
    startHref: "/activos/mot/nuevo",
    roles: "qa.ventas.systron, qa.gerente.sm, qa.ceo, qa.coordinacion",
  },
  {
    id: "R-07",
    title: "Cliente directo Servomotores",
    discovery: "§1.4, §4.x SM",
    priority: "secundario",
    startHref: "/comercial/clientes/nuevo",
    roles: "qa.gerente.sm, qa.ceo",
  },
  {
    id: "R-08",
    title: "Garantía SYSTRON / MOT SM",
    discovery: "§4.5",
    priority: "secundario",
    startHref: "/operacion/atenciones/nueva",
    roles: "qa.gerente.systron, qa.ceo",
  },
  {
    id: "R-09",
    title: "Servicio externo en diagnóstico",
    discovery: "§4.3 externo",
    priority: "secundario",
    startHref: "/operacion/diagnosticos",
    roles: "qa.gerente.systron, qa.coordinacion",
  },
  {
    id: "R-10",
    title: "Refacciones en OS",
    discovery: "§4.4",
    priority: "secundario",
    startHref: "/operacion/os",
    roles: "qa.tecnico.systron, qa.almacen.systron",
  },
  {
    id: "R-11",
    title: "Movimientos físicos (ingreso, prueba, egreso)",
    discovery: "§4.6",
    priority: "secundario",
    startHref: "/activos/almacen",
    roles: "qa.almacen.systron, qa.gerente.sm",
  },
  {
    id: "R-12",
    title: "Compras directas y O.C.",
    discovery: "§6",
    priority: "secundario",
    startHref: "/operacion/compras",
    roles: "qa.gerente.systron, qa.ceo, qa.coordinacion",
  },
  {
    id: "R-13",
    title: "Factura, remisión, pago, cobranza",
    discovery: "§7",
    priority: "nucleo",
    startHref: "/administracion/facturacion?vista=pendientes",
    roles: "qa.ventas.systron, qa.coordinacion",
  },
  {
    id: "R-14",
    title: "Intercompañía fiscal CxC/CxP",
    discovery: "§7 intercompañía",
    priority: "nucleo",
    startHref: "/administracion/cxp",
    roles: "qa.coordinacion, qa.ceo",
  },
  {
    id: "R-15",
    title: "Vacaciones",
    discovery: "§9",
    priority: "secundario",
    startHref: "/capital-humano/vacaciones",
    roles: "jefe + qa.ceo",
  },
  {
    id: "R-16",
    title: "Kiosco asistencia",
    discovery: "§9",
    priority: "secundario",
    startHref: "/kiosco",
    roles: "qa.kiosco",
  },
  {
    id: "R-17",
    title: "Nómina semanal",
    discovery: "§9.2",
    priority: "secundario",
    startHref: "/capital-humano/nomina",
    roles: "qa.coordinacion, qa.ceo",
  },
  {
    id: "R-18",
    title: "Horas extra",
    discovery: "§9",
    priority: "secundario",
    startHref: "/capital-humano/mis-horas-extra",
    roles: "qa.tecnico.systron, qa.ceo",
  },
  {
    id: "R-19",
    title: "Venta de equipo",
    discovery: "§5",
    priority: "secundario",
    startHref: "/comercial/cotizaciones/nueva",
    roles: "qa.ventas.systron, qa.ceo",
  },
  {
    id: "R-20",
    title: "Servicio en campo",
    discovery: "§5",
    priority: "secundario",
    startHref: "/comercial/cotizaciones/nueva",
    roles: "qa.ventas.systron, qa.ceo",
  },
  {
    id: "R-21",
    title: "Comisiones mensuales",
    discovery: "§9",
    priority: "secundario",
    startHref: "/capital-humano/comisiones",
    roles: "qa.coordinacion, qa.ceo",
  },
  {
    id: "R-22",
    title: "Producción técnica SYSTRON",
    discovery: "§8",
    priority: "secundario",
    startHref: "/administracion/produccion-tecnica",
    roles: "qa.tecnico.systron, qa.gerente.systron",
  },
];
